#!/bin/bash

CONFIG_DIR="$HOME/.deb-updater"
MSMTP_CONFIG="$HOME/.msmtprc"
GPG_PASS_FILE="$CONFIG_DIR/.email-password.gpg"

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"

# === Prompt User for Provider and Email ===
EMAIL=$(zenity --entry --title="Email Setup" --text="Enter your full email address (e.g. tim@example.com):")
if [[ -z "$EMAIL" ]]; then
    zenity --error --text="Email address is required."
    exit 1
fi

PROVIDER=$(zenity --list --title="Choose Email Provider" --column="Provider" Gmail Outlook Yahoo Custom)
if [[ -z "$PROVIDER" ]]; then
    zenity --error --text="You must choose an email provider."
    exit 1
fi

# === Set SMTP settings ===
case "$PROVIDER" in
  Gmail)
    HOST="smtp.gmail.com"
    PORT=587
    TLS="on"
    NOTE="To continue, you'll need a Google App Password."
    ;;
  Outlook)
    HOST="smtp.office365.com"
    PORT=587
    TLS="on"
    NOTE="You'll need your Outlook email password or app password."
    ;;
  Yahoo)
    HOST="smtp.mail.yahoo.com"
    PORT=587
    TLS="on"
    NOTE="Yahoo typically requires an app password."
    ;;
  Custom)
    HOST=$(zenity --entry --title="Custom SMTP" --text="Enter your SMTP host:")
    PORT=$(zenity --entry --title="Custom SMTP" --text="Enter your SMTP port:")
    TLS="on"
    NOTE="Your server must support STARTTLS."
    ;;
esac

zenity --info --title="App Password Notice" --text="$NOTE"

# === Check for existing GPG keys ===
KEY_COUNT=$(gpg --list-keys | grep -c '^pub')
if [[ "$KEY_COUNT" -eq 0 ]]; then
    zenity --question --title="No GPG Key" --text="No GPG keys found. Generate one now?"
    if [[ $? -eq 0 ]]; then
        gpg --full-generate-key
    else
        zenity --error --text="A GPG key is required for encrypted password storage."
        exit 1
    fi
fi

# === Encrypt Password ===
APP_PASS=$(zenity --password --title="Enter App Password")
echo "$APP_PASS" | gpg --yes --batch -o "$GPG_PASS_FILE" -e -r "$EMAIL"
chmod 600 "$GPG_PASS_FILE"

# === Write ~/.msmtprc ===
cat > "$MSMTP_CONFIG" <<EOF
# Generated by Deb Updater Setup
account default
host $HOST
port $PORT
auth on
user $EMAIL
from $EMAIL
passwordeval gpg --quiet --for-your-eyes-only --no-tty --decrypt $GPG_PASS_FILE
tls $TLS
tls_starttls on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile $CONFIG_DIR/msmtp.log
EOF

chmod 600 "$MSMTP_CONFIG"
echo "✅ Email configuration complete."
zenity --info --text="✅ Encrypted password saved and email configuration complete."
